version: '3.7'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   env_file:
  #     - docker.env
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=penca_ucu
      - MYSQL_USER=usr_penca
      - MYSQL_PASSWORD=12345678

volumes:
  db_data: