name: Deploy to Raspi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Deployment Script on Remote Server
      run: ssh -o StrictHostKeyChecking=no nico@nicocartalla.ddns.net -p 22322 /home/nico/bd2/deploy-db.sh
